services:
  uptime-kuma:
    image: louislam/uptime-kuma:2
    container_name: uptime-kuma
    ports:
      - "${UPTIME_KUMA_PORT}:3001"
    volumes:
      - uptime-kuma-data:/app/data
    restart: unless-stopped
    environment:
      - UPTIME_KUMA_DB_TYPE=sqlite
      - UPTIME_KUMA_DB_NAME=kuma
      - UPTIME_KUMA_DB_USERNAME=kuma
      - UPTIME_KUMA_DB_PASSWORD=kuma

    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3001 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  uptime-kuma-data:
